---

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-adguard-home.git
  version: v0.107.40-0
  name: adguard_home
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-appsmith.git
  version: v1.9.41-0
  name: appsmith
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-authelia.git
  version: v4.37.5-0
  name: authelia
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-authentik.git
  version: v2023.8.3-1
  name: authentik
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-aux.git
  version: v1.0.0-1
  name: auxiliary
- src: git+https://gitlab.com/etke.cc/roles/backup_borg.git
  version: v1.2.6-1.8.4-0
- src: git+https://github.com/nielscil/ansible-role-changedetection.git
  version: v0.45.5-0
  name: changedetection
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-clickhouse.git
  version: v23.6.1.1524-0
  name: clickhouse
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-collabora-online.git
  version: v22.05.13.1.1-0
  name: collabora_online
- src: git+https://github.com/devture/com.devture.ansible.role.container_socket_proxy.git
  version: v0.1.1-2
- src: git+https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python.git
  version: 129c8590e106b83e6f4c259649a613c6279e937a
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_help.git
  version: c1f40e82b4d6b072b6f0e885239322bdaaaf554f
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_runtime_messages.git
  version: 9b4b088c62b528b73a9a7c93d3109b091dd42ec6
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_state_preserver.git
  version: ff2fd42e1c1a9e28e3312bbd725395f9c2fc7f16
- src: git+https://github.com/devture/com.devture.ansible.role.postgres.git
  version: v16.0-8
- src: git+https://github.com/devture/com.devture.ansible.role.postgres_backup.git
  version: d2c2585fe3f5ebf39045bc90c97ee160e1341594
- src: git+https://github.com/devture/com.devture.ansible.role.systemd_docker_base.git
  version: v1.0.0-0
- src: git+https://github.com/devture/com.devture.ansible.role.systemd_service_manager.git
  version: v1.0.0-1
- src: git+https://github.com/devture/com.devture.ansible.role.timesync.git
  version: v1.0.0-0
- src: git+https://github.com/devture/com.devture.ansible.role.traefik.git
  version: v2.10.5-1
- src: git+https://github.com/devture/com.devture.ansible.role.woodpecker_ci_agent.git
  version: v1.0.5-0
- src: git+https://github.com/devture/com.devture.ansible.role.woodpecker_ci_server.git
  version: v1.0.5-0
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry.git
  version: v2.8.3-0
  name: docker_registry
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry-browser.git
  version: v1.6.1-0
  name: docker_registry_browser
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry-purger.git
  version: v1.0.0-0
  name: docker_registry_purger
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-echoip.git
  version: v0.0.0-0
  name: echoip
- src: git+https://gitlab.com/etke.cc/roles/fail2ban.git
  version: 09886730e8d3c061f22d1da4a542899063f97f0a
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-firezone.git
  version: v0.7.35-0
  name: firezone
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-focalboard.git
  version: v7.10.4-0
  name: focalboard
- src: git+https://github.com/NeonMinnen/ansible-role-forgejo.git
  version: v1.20.4-1-1
  name: forgejo
- src: git+https://github.com/kinduff/ansible-docker-freshrss.git
  version: v2.1.0
  name: freshrss
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-funkwhale.git
  version: v1.3.1-0
  name: funkwhale
- src: git+https://github.com/geerlingguy/ansible-role-docker
  version: 7.0.1
  name: geerlingguy.docker
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gitea.git
  version: v1.20.5-0
  name: gitea
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gotosocial.git
  version: v0.12.1-1
  name: gotosocial
- src: git+https://gitlab.com/etke.cc/roles/grafana.git
  version: v10.2.0-0
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-healthchecks.git
  version: v3.0.1-0
  name: healthchecks
- src: git+https://github.com/moan0s/hubsite.git
  version: v1.25.2-0
  name: hubsite
- src: git+https://github.com/moan0s/ansible-role-ilmo.git
  version: v1.0.4-0
  name: ilmo
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-infisical.git
  version: v0.3.8-4
  name: infisical
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-influxdb.git
  version: v2.7.0-3
  name: influxdb
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-jitsi.git
  version: v8960-3
  name: jitsi
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-keycloak.git
  version: v22.0.5-0
  name: keycloak
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-lago.git
  version: v0.50.0-0
  name: lago
- src: git+https://github.com/kinduff/ansible-docker-linkding.git
  version: v1.9.0
  name: linkding
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-mariadb.git
  version: v10.11.4-0
  name: mariadb
- src: git+https://gitlab.com/etke.cc/roles/miniflux.git
  version: v2.0.49-0
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-mobilizon.git
  version: v3.1.3-0
  name: mobilizon
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-mongodb.git
  version: v7.0.2-0
  name: mongodb
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-mosquitto.git
  version: v2.0.15-1
  name: mosquitto
- src: git+https://gitlab.com/etke.cc/mrs/ansible-role-mrs.git
  version: v0.0.0-20
  name: mrs
- src: git+https://github.com/kinduff/ansible-docker-n8n.git
  version: v1.4.2
  name: n8n
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-navidrome.git
  version: v0.49.3-2
  name: navidrome
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-netbox.git
  version: v3.6.0-2.7.0-0
  name: netbox
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-nextcloud.git
  version: v27.1.1-1
  name: nextcloud
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-outline.git
  version: v0.72.0-0-0
  name: outline
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-owncast.git
  version: v0.1.1-1
  name: owncast
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-oxitraffic.git
  version: v0.7.0-1
  name: oxitraffic
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-peertube.git
  version: v5.2.1-0
  name: peertube
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-postgis.git
  version: v15-3.3-0
  name: postgis
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus.git
  version: v2.47.2-0
  name: prometheus
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus-blackbox-exporter.git
  version: v0.24.0-0
  name: prometheus_blackbox_exporter
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus-node-exporter.git
  version: v1.6.1-0
  name: prometheus_node_exporter
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus-postgres-exporter.git
  version: v0.14.0-0
  name: prometheus_postgres_exporter
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus-ssh-exporter.git
  version: v1.5.0-0
  name: prometheus_ssh_exporter
- src: git+https://gitlab.com/etke.cc/roles/radicale.git
  version: v3.1.8.3-0
- src: git+https://gitlab.com/etke.cc/roles/redis.git
  version: v7.2.0-0
- src: git+https://gitlab.com/etke.cc/roles/redmine.git
  version: v5.1.0-0
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-roundcube.git
  version: v1.6.3-0
  name: roundcube
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-rumqttd.git
  version: v0.21.0-0
  name: rumqttd
- src: git+https://gitlab.com/etke.cc/roles/soft_serve.git
  version: v0.4.7-0
- src: git+https://gitlab.com/etke.cc/roles/ssh.git
  version: 13440992374e0fef8f6360a0856b78b37a1fd831
- src: git+https://gitlab.com/etke.cc/roles/swap.git
  version: abfb18b6862108bbf24347500446203170324d7f
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-syncthing.git
  version: v1.26.0-0
  name: syncthing
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-telegraf.git
  version: v1.27.1-2
  name: telegraf
- src: git+https://gitlab.com/etke.cc/roles/uptime_kuma.git
  version: v1.23.3-0
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-vaultwarden.git
  version: v1.30.0-0
  name: vaultwarden
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-wg-easy.git
  version: v7-0
  name: wg_easy
