---
galaxy_info:
  author: Oliver Lorenz
  role_name: oliverlorenz_api
  namespace: oliverlorenz
  description: Oliver Lorenz API
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: EL
      versions:
        - all
  license: AGPL-3.0-or-later
  min_ansible_version: "2.1"
