# SPDX-FileCopyrightText: 2026 Oliver Lorenz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of app-dooropener systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ app_dooropener_identifier }}.service"
  register: app_dooropener_service_stat

- name: Uninstall app-dooropener systemd services and files
  when: app_dooropener_service_stat.stat.exists | bool
  block:
    - name: Ensure app-dooropener systemd service is stopped
      ansible.builtin.service:
        name: "{{ app_dooropener_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure app-dooropener systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ app_dooropener_identifier }}.service"
        state: absent

    - name: Ensure app-dooropener container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ app_dooropener_container_network }}"
        state: absent

    - name: Ensure app-dooropener container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ app_dooropener_container_network }}
      register: network_deletion_result
      changed_when: app_dooropener_container_network in network_deletion_result.stdout

    - name: Ensure app-dooropener path does not exist
      ansible.builtin.file:
        path: "{{ app_dooropener_base_path }}"
        state: absent
