---
galaxy_info:
  author: Oliver Lorenz
  role_name: ohrwurm
  namespace: oliverlorenz
  description: ohrwurm-app (SongScan/Playlist/Multiplayer music party webapp)
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: EL
      versions:
        - all
  license: AGPL-3.0-or-later
  min_ansible_version: "2.1"
