# SPDX-FileCopyrightText: 2025 Oliver Lorenz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of API systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ oliverlorenz_api_identifier }}.service"
  register: oliverlorenz_api_service_stat

- name: Uninstall API systemd services and files
  when: oliverlorenz_api_service_stat.stat.exists | bool
  block:
    - name: Ensure API systemd service is stopped
      ansible.builtin.service:
        name: "{{ oliverlorenz_api_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure API systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ oliverlorenz_api_identifier }}.service"
        state: absent

    - name: Ensure API container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ oliverlorenz_api_container_network }}"
        state: absent

    - name: Ensure API container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ oliverlorenz_api_container_network }}
      register: network_deletion_result
      changed_when: oliverlorenz_api_container_network in network_deletion_result.stdout

    - name: Ensure API path does not exist
      ansible.builtin.file:
        path: "{{ oliverlorenz_api_base_path }}"
        state: absent
