# SPDX-FileCopyrightText: 2025 Oliver Lorenz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Restart GOWA
  ansible.builtin.systemd:
    name: "{{ gowa_identifier }}.service"
    state: restarted
  listen: "gowa-restart"
