---

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-adguard-home.git
  version: v0.107.59-0
  name: adguard_home
  activation_prefix: adguard_home_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-anonymousoverflow.git
  version: v2024.8.23-0
  name: anonymousoverflow
  activation_prefix: anonymousoverflow_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-apisix-dashboard.git
  version: v3.0.1-0
  name: apisix_dashboard
  activation_prefix: apisix_dashboard_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-apisix-gateway.git
  version: v3.8.0-2
  name: apisix_gateway
  activation_prefix: apisix_gateway_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-appsmith.git
  version: v1.9.50-0
  name: appsmith
  activation_prefix: appsmith_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-authelia.git
  version: v4.37.5-1
  name: authelia
  activation_prefix: authelia_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-authentik.git
  version: v2025.2.2-0
  name: authentik
  activation_prefix: authentik_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-aux.git
  version: v1.0.0-5
  name: auxiliary
  activation_prefix: aux_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-backup_borg.git
  version: v1.4.0-1.9.13-1
  name: backup_borg
  activation_prefix: backup_borg_
- src: git+https://github.com/lingawakad/ansible-role-calibre-web.git
  version: v0.6.24-0
  name: calibre-web
  activation_prefix: calibre-web_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-changedetection.git
  version: v0.48.04-0
  name: changedetection
  activation_prefix: changedetection_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-cleanup.git
  version: main
  name: cleanup
  activation_prefix: system_cleanup_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-clickhouse.git
  version: v25.2.2.39-0
  name: clickhouse
  activation_prefix: clickhouse_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-collabora-online.git
  version: v24.04.13.2.1-0
  name: collabora_online
  activation_prefix: collabora_online_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-container-socket-proxy.git
  version: v0.3.0-4
  name: container_socket_proxy
  activation_prefix: mash_
- src: git+https://github.com/Bergruebe/ansible-role-couchdb.git
  version: v3.4.3-0
  name: couchdb
  activation_prefix: couchdb_
- src: git+https://github.com/geerlingguy/ansible-role-docker
  version: 7.4.7
  name: docker
  activation_prefix: mash_playbook_docker_installation_enabled
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry.git
  version: v2.8.3-5
  name: docker_registry
  activation_prefix: docker_registry_enabled
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry-browser.git
  version: v1.7.5-0
  name: docker_registry_browser
  activation_prefix: docker_registry_browser_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry-proxy.git
  version: v1.2.5-0
  name: docker_registry_proxy
  activation_prefix: docker_registry_proxy_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry-purger.git
  version: v1.0.0-1
  name: docker_registry_purger
  activation_prefix: docker_registry_purger_
- src: git+https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python.git
  version: 129c8590e106b83e6f4c259649a613c6279e937a
  name: docker_sdk_for_python
  activation_prefix: devture_docker_sdk_for_python_installation_enabled
- src: git+https://github.com/shukon/ansible-role-dokuwiki.git
  version: v2024-02-06b-2
  name: dokuwiki
  activation_prefix: dokuwiki_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-echoip.git
  version: v0.0.0-1
  name: echoip
  activation_prefix: echoip_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-endlessh.git
  version: v2024.0119.1-0
  name: endlessh
  activation_prefix: endlessh_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-etcd.git
  version: v3.5.11-0
  name: etcd
  activation_prefix: etcd_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-etherpad.git
  version: v2.2.7-4
  name: etherpad
  activation_prefix: etherpad_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-exim-relay.git
  version: v4.98.1-r0-2-0
  name: exim_relay
  activation_prefix: exim_relay_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-fail2ban.git
  version: e25d0d9b5282dbb5a1ec4cd23d26c16998e4334f
  name: fail2ban
  activation_prefix: system_security_fail2ban_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-firezone.git
  version: v0.7.36-3
  name: firezone
  activation_prefix: firezone_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-focalboard.git
  version: v7.10.4-0
  name: focalboard
  activation_prefix: focalboard_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-forgejo.git
  version: v10.0.2-0
  name: forgejo
  activation_prefix: forgejo_
- src: git+https://git.sergiodj.net/sergiodj/ansible-role-forgejo-runner.git
  version: v6.2.0-0
  name: forgejo_runner
  activation_prefix: forgejo_runner_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-freescout.git
  version: v1.17.110-1
  name: freescout
  activation_prefix: freescout_
- src: git+https://github.com/kinduff/ansible-docker-freshrss.git
  version: v2.5.0
  name: freshrss
  activation_prefix: freshrss_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-funkwhale.git
  version: v1.4.0-9
  name: funkwhale
  activation_prefix: funkwhale_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gitea.git
  version: v1.23.5-2
  name: gitea
  activation_prefix: gitea_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gotosocial.git
  version: v0.18.3-1
  name: gotosocial
  activation_prefix: gotosocial_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-grafana.git
  version: v11.6.0-0
  name: grafana
  activation_prefix: grafana_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-headscale.git
  version: v0.25.1-3
  name: headscale
  activation_prefix: headscale_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-healthchecks.git
  version: v3.9-2
  name: healthchecks
  activation_prefix: healthchecks_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-hubsite.git
  version: v1.27.4-1
  name: hubsite
  activation_prefix: hubsite_
- src: git+https://github.com/IUCCA/ansible-role-ihatemoney.git
  version: v6.1.5-7
  name: ihatemoney
  activation_prefix: ihatemoney_
- src: git+https://github.com/moan0s/ansible-role-ilmo.git
  version: v1.0.4-0
  name: ilmo
  activation_prefix: ilmo_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-infisical.git
  version: v0.43.19-0
  name: infisical
  activation_prefix: infisical_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-influxdb.git
  version: v2.7.6-0
  name: influxdb
  activation_prefix: influxdb_
- src: git+https://github.com/spatterIight/ansible-role-jackett.git
  version: v0.22.1660-0
  name: jackett
  activation_prefix: jackett_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-jitsi.git
  version: v10133-1-0
  name: jitsi
  activation_prefix: jitsi_
- src: git+https://codeberg.org/acioustick/ansible-role-joplin-server.git
  version: v3.3.13-0
  name: joplin_server
  activation_prefix: joplin_server_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-keycloak.git
  version: v26.1.3-0
  name: keycloak
  activation_prefix: keycloak_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-keydb.git
  version: v6.3.4-3
  name: keydb
  activation_prefix: keydb_
- src: git+https://gitlab.com/horvathg.1988/ansible-role-labelstudio.git
  version: v1.0.0-3
  name: labelstudio
  activation_prefix: labelstudio_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-lago.git
  version: v0.50.0-0
  name: lago
  activation_prefix: lago_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-languagetool.git
  version: v6.5-3
  name: languagetool
  activation_prefix: languagetool_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-linkding.git
  version: v1.39.1-0
  name: linkding
  activation_prefix: linkding_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-loki.git
  version: v2.9.4-3
  name: loki
  activation_prefix: loki_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-mariadb.git
  version: v11.4.4-2
  name: mariadb
  activation_prefix: mariadb_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-matterbridge.git
  version: v1.26.0-0
  name: matterbridge
  activation_prefix: matterbridge_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-miniflux.git
  version: v2.2.4-3
  name: miniflux
  activation_prefix: miniflux_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-mobilizon.git
  version: v4.1.0-0
  name: mobilizon
  activation_prefix: mobilizon_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-mongodb.git
  version: v7.0.4-0
  name: mongodb
  activation_prefix: mongodb_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-mosquitto.git
  version: v2.0.15-1
  name: mosquitto
  activation_prefix: mosquitto_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-mrs.git
  version: v0.1.0-2
  name: mrs
  activation_prefix: mrs_
- src: git+https://github.com/kinduff/ansible-docker-n8n.git
  version: v1.4.2
  name: n8n
  activation_prefix: n8n_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-navidrome.git
  version: v0.55.1-0
  name: navidrome
  activation_prefix: navidrome_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-neko.git
  version: v2.8.12-0
  name: neko
  activation_prefix: neko_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-netbox.git
  version: v3.7.0-2.8.0-0
  name: netbox
  activation_prefix: netbox_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-nextcloud.git
  version: v31.0.2-0
  name: nextcloud
  activation_prefix: nextcloud_
- src: git+https://codeberg.org/moanos/ansible-role-notfellchen.git
  version: v0.4.0-0
  name: notfellchen
  activation_prefix: notfellchen_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-ntfy.git
  version: v2.11.0-4
  name: ntfy
  activation_prefix: ntfy_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-oauth2-proxy.git
  version: v7.6.0-1
  name: oauth2_proxy
  activation_prefix: oauth2_proxy_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-outline.git
  version: v0.82.0-0
  name: outline
  activation_prefix: outline_
- src: git+https://github.com/spatterIight/ansible-role-overseerr.git
  version: v1.33.2-1
  name: overseerr
  activation_prefix: overseerr_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-owncast.git
  version: v0.2.1-2
  name: owncast
  activation_prefix: owncast_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-oxitraffic.git
  version: v0.10.1-0
  name: oxitraffic
  activation_prefix: oxitraffic_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-paperless.git
  version: v2.13.2-0
  name: paperless
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-peertube.git
  version: v7.0.1-2
  name: peertube
  activation_prefix: peertube_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-plausible.git
  version: v2.1.5-1
  name: plausible
  activation_prefix: plausible_
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_help.git
  version: 201c939eed363de269a83ba29784fc3244846048
  name: playbook_help
  activation_prefix: ""
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_runtime_messages.git
  version: 9b4b088c62b528b73a9a7c93d3109b091dd42ec6
  name: playbook_runtime_messages
  activation_prefix: ""
- src: git+https://github.com/devture/com.devture.ansible.role.playbook_state_preserver.git
  version: ff2fd42e1c1a9e28e3312bbd725395f9c2fc7f16
  name: playbook_state_preserver
  activation_prefix: devture_playbook_state_preserver_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-postgis.git
  version: v15-3.3-0
  name: postgis
  activation_prefix: postgis_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-postgres.git
  version: v17.4-0
  name: postgres
  activation_prefix: postgres_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-postgres-backup.git
  version: v17-3
  name: postgres_backup
  activation_prefix: postgres_backup_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus.git
  version: v2.55.1-3
  name: prometheus
  activation_prefix: prometheus_enabled
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus-blackbox-exporter.git
  version: v0.25.0-1
  name: prometheus_blackbox_exporter
  activation_prefix: prometheus_blackbox_exporter_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus-node-exporter.git
  version: v1.8.2-5
  name: prometheus_node_exporter
  activation_prefix: prometheus_node_exporter_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus-postgres-exporter.git
  version: v0.14.0-9
  name: prometheus_postgres_exporter
  activation_prefix: prometheus_postgres_exporter_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus-ssh-exporter.git
  version: v1.5.0-2
  name: prometheus_ssh_exporter
  activation_prefix: prometheus_ssh_exporter_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-promtail.git
  version: v2.9.5-0
  name: promtail
  activation_prefix: promtail_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-qbittorrent.git
  version: v5.0.4-1
  name: qbittorrent
  activation_prefix: qbittorrent_
- src: git+https://github.com/spatterIight/ansible-role-radarr.git
  version: v5.19.3-0
  name: radarr
  activation_prefix: radarr_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-radicale.git
  version: v3.5.0.0-0
  name: radicale
  activation_prefix: radicale_
- src: git+https://github.com/lingawakad/ansible-role-readeck.git
  version: v0.17.1-0
  name: readeck
  activation_prefix: readeck_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-redis.git
  version: v7.4.2-0
  name: redis
  activation_prefix: redis_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-redmine.git
  version: v6.0.4-2
  name: redmine
  activation_prefix: redmine_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-roundcube.git
  version: v1.6.10-1
  name: roundcube
  activation_prefix: roundcube_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-rumqttd.git
  version: v0.21.0-0
  name: rumqttd
  activation_prefix: rumqttd_
- src: git+https://git.sergiodj.net/sergiodj/ansible-role-searxng.git
  version: v1.0-0
  name: searxng
  activation_prefix: searxng_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-semaphore.git
  version: v2.9.56-0
  name: semaphore
  activation_prefix: semaphore_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-send.git
  version: v2025.2.4-0
  name: send
  activation_prefix: send_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-soft_serve.git
  version: v0.4.7-1
  name: soft_serve
  activation_prefix: soft_serve_
- src: git+https://github.com/spatterIight/ansible-role-sonarr.git
  version: v4.0.14-0
  name: sonarr
  activation_prefix: sonarr_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-ssh.git
  version: 13440992374e0fef8f6360a0856b78b37a1fd831
  name: ssh
  activation_prefix: system_security_ssh_
- src: git+https://github.com/Bergruebe/ansible-role-stirling-pdf.git
  version: v0.45.0-1
  name: stirling_pdf
  activation_prefix: stirling_pdf_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-swap.git
  version: abfb18b6862108bbf24347500446203170324d7f
  name: swap
  activation_prefix: system_swap_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-syncthing.git
  version: v1.29.4-0
  name: syncthing
  activation_prefix: syncthing_
- src: git+https://github.com/devture/com.devture.ansible.role.systemd_docker_base.git
  version: v1.4.0-0
  name: systemd_docker_base
  activation_prefix: ""
- src: git+https://github.com/devture/com.devture.ansible.role.systemd_service_manager.git
  version: v1.0.0-4
  name: systemd_service_manager
  activation_prefix: ""
- src: git+https://github.com/IUCCA/ansible-role-tandoor.git
  version: v1.5.34-1
  name: tandoor
  activation_prefix: tandoor_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-telegraf.git
  version: v1.30.2-0
  name: telegraf
  activation_prefix: telegraf_
- src: git+https://github.com/devture/com.devture.ansible.role.timesync.git
  version: v1.0.0-0
  name: timesync
  activation_prefix: devture_timesync_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-traefik.git
  version: v3.3.5-0
  name: traefik
  activation_prefix: mash_
- src: git+https://github.com/Bergruebe/ansible-role-tsdproxy.git
  version: v1.4.4-1
  name: tsdproxy
  activation_prefix: tsdproxy_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-uptime_kuma.git
  version: v1.23.16-2
  name: uptime_kuma
  activation_prefix: uptime_kuma_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-valkey.git
  version: v8.0.1-3
  name: valkey
  activation_prefix: valkey_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-vaultwarden.git
  version: v1.33.2-3
  name: vaultwarden
  activation_prefix: vaultwarden_
- src: git+https://github.com/moan0s/ansible-role-versatiles.git
  version: v0.15.3-0
  name: versatiles
  activation_prefix: versatiles_
- src: git+https://github.com/spatterIight/ansible-role-wetty.git
  version: v2.5-0
  name: wetty
  activation_prefix: wetty_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-wg-easy.git
  version: v14-3
  name: wg_easy
  activation_prefix: wg_easy_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-woodpecker-ci-agent.git
  version: v3.1.0-0
  name: woodpecker_ci_agent
  activation_prefix: woodpecker_ci_agent_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-woodpecker-ci-server.git
  version: v3.1.0-0
  name: woodpecker_ci_server
  activation_prefix: woodpecker_ci_server_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-wordpress
  version: v6.6.2-0
  name: wordpress
  activation_prefix: wordpress_
- src: git+https://github.com/ZenKyma/ansible-role-writefreely.git
  version: v0.15.0-1
  name: writefreely
  activation_prefix: writefreely_
- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-yourls.git
  version: v1.9.2-1
  name: yourls
  activation_prefix: yourls_
