# SPDX-FileCopyrightText: 2026 Oliver Lorenz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform ohrwurm installation tasks
  when: ohrwurm_enabled | bool
  tags:
    - setup-all
    - setup-ohrwurm
    - install-all
    - install-ohrwurm
  block:
    - name: Validate ohrwurm configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install ohrwurm
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform ohrwurm uninstallation tasks
  when: not ohrwurm_enabled | bool
  tags:
    - setup-all
    - setup-ohrwurm
  block:
    - name: Uninstall ohrwurm
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
