# SPDX-FileCopyrightText: 2026 Oliver Lorenz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required ohrwurm settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - ohrwurm_container_network

- name: Run if Traefik is enabled
  when: ohrwurm_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for ohrwurm are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - ohrwurm_container_labels_traefik_hostname
        - ohrwurm_container_labels_traefik_path_prefix
